name: Install Dependencies and Push to PWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create custom-wheels directory
      run: mkdir -p ./custom-wheels

    - name: Download wheels
      run: pip download -r requirements.txt -d ./custom-wheels

    - name: Set up Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Check PWS remote and push
      run: |
        PWS_URL="http://${{ secrets.PWS_USERNAME }}:${{ secrets.PWS_PASSWORD }}@pbp.cs.ui.ac.id/isa.citra/elf"
        if git remote | grep -q "^pws$"; then
          echo "PWS remote exists. Updating URL."
          git remote set-url pws "$PWS_URL"
        else
          echo "PWS remote does not exist. Adding it."
          git remote add pws "$PWS_URL"
        fi
        git add .
        git commit -m "Add installed dependencies and custom wheels" || echo "No changes to commit"
        git push pws master
      env:
        GIT_TERMINAL_PROMPT: 0